import Head from 'next/head'
import AnimationLogo from './components/AnimationLogo'
import CardUser from './components/CardUser'
import NavBar from './components/NavBar'
import { useState } from "react";
import axios from 'axios'
import { useEffect } from 'react';
import Loading from './components/Loading';

export default function Home() {
  const [show, setShow] = useState(true);
  const [rest, setRest] = useState([])

  const getData = async () => {
    const response = await axios.get('/api/user')
     const  data = await response.data
   if(data) {
     setRest(data)
   }
}

useEffect(()=>{
 getData()
},[])

   const handleShow = () => {
       setShow(!show);

   }

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
        <AnimationLogo/>

        <div className="user">
           <NavBar show={show} handleShow={handleShow} main={false} active={false}></NavBar>
          <div className="interfaceUser">
              <div className="titleUser">
                 <h1>{show ? "Who's watching ?": "Manage Profiles"}</h1>
              </div>

           <div className="showCardUser">
              <div id="showCardUser">
                {rest.length >= 1 && rest.map((user, i)=> (
                            <CardUser user={user} key={i} show={show}/>
                ))}
              </div>


           </div>
          </div>
        </div>
        
    </div>
  )
}
